### ISSUE TITLE
code: -32601, message: 'Method not found'

### ISSUE THREAD

**Issue by Wangmmx** [rmrk-team/rmrk-tools#73]
When I tried to get nonce from chain by `system_accountNextIndex`, it got the error:
`code: -32601, message: 'Method not found'`

This api is a common JSON-RPC api of polkadot, so is that a bug need fixed?

**Comment by Yuripetusko** [comment]
Can you give more details p[lease. How do you call `system_accountNextIndex ` and why?

**Comment by Wangmmx** [comment]
Yes, I want to transfer so that I need my address nonce
I just use the polkadot JSON-RPC api to get it, here is the link https://polkadot.js.org/docs/substrate/rpc/#system
And wait a moment, I will give you some curl commands

**Comment by Yuripetusko** [comment]
What are you trying to transfer? RMRK NFTs?

**Comment by Wangmmx** [comment]
> What are you trying to transfer? RMRK NFTs?

Yes, RMRK

**Comment by Swader** [comment]
You don't need nonces to do transfers, use auto-incrementer: https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce

As a user of the API and not a wallet developer, you should never have to care about nonces.

**Comment by Wangmmx** [comment]
> You don't need nonces to do transfers, use auto-incrementer: https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce
> 
> As a user of the API and not a wallet developer, you should never have to care about nonces.

I build the txBody offline, and send it to the chain, so I need nonce to do it, I am a wallet app developer, should I ask statemine to fix the bug?

**Comment by Swader** [comment]
Ah you're transferring fungibles? Not NFTs but RMRK tokens? Then yes, it's probably missing RPCs in Statemine nodes and [needs an issue](https://github.com/paritytech/cumulus/issues), but V4 is tagged for a release soon and those should be in, I hope. If not you will have to wait for yet another release. In any case make an issue ASAP

**Comment by Swader** [comment]
Just drop an issue here and they will reply: https://github.com/paritytech/cumulus/issues
