### ISSUE TITLE
Node startup failure

### ISSUE THREAD

**Issue by COLUD4** [rmrk-team/rmrk-tools#78]
I'm in here (https://github.com/paritytech/polkadot) after steps to build the node cannot be started, this is my startup command ( /mnt/ksmsmmain/core/polkadot/target/release/polkadot --chain statemine --base-path /mnt/ksmsmmain/node --unsafe-pruning --pruning 5000 --port 9001 --ws-port 25500 --rpc-external  --ws-external --ws-max-connections=20 --rpc-cors '*
![截屏2021-11-30 下午5 59 15](https://user-images.githubusercontent.com/21240219/144026123-d2205261-e6e4-4af6-b4c8-253bd1e0bee0.png)
')

**Comment by Yuripetusko** [comment]
Why are you trying to run a statemine?

**Comment by COLUD4** [comment]
> What should the chain argument be

**Comment by Yuripetusko** [comment]
Check out this

https://docs.rmrk.app/syncing/

**Comment by COLUD4** [comment]
![Uploading 截屏2021-11-30 下午7.01.15.png…](
![截屏2021-11-30 下午7 00 13](https://user-images.githubusercontent.com/21240219/144035525-e2de9168-da4f-4c0e-ae74-1af04eab0a92.png)
)

This block height does not match

**Comment by COLUD4** [comment]
![截屏2021-11-30 下午7 01 15](https://user-images.githubusercontent.com/21240219/144035656-94f93aff-bb7e-46ff-8d28-3be09b8ee4c1.png)

**Comment by Yuripetusko** [comment]
Try adding `--dev --tmp` flags.

**Comment by COLUD4** [comment]
![截屏2021-11-30 下午7 08 42](https://user-images.githubusercontent.com/21240219/144036611-2f508ba1-7521-4fd3-b68c-504793cc1163.png)

**Comment by Yuripetusko** [comment]
yeah so now you have an empty local dev chain. Unless You are trying to do something else? But I still don't understand what are you trying to do and why do you need a statemine

**Comment by COLUD4** [comment]
I need to set up a main network node to use

**Comment by Yuripetusko** [comment]
how is it related to RMRK?

**Comment by COLUD4** [comment]
I need to build a node, read the block height from the node, and so on
![截屏2021-11-30 下午7 15 35](https://user-images.githubusercontent.com/21240219/144037767-88c87ad6-cb10-4d2f-b878-b6fc4727abc2.png)

**Comment by Swader** [comment]
Instructions for running a Statemine live node are here: https://wiki.polkadot.network/docs/build-integrate-assets

**Comment by COLUD4** [comment]
https://github.com/rmrk-team/rmrk-tools/issues/78#issue-1067029360
This document construct node is the same as here, it does not perform as desired node, block height does not match

**Comment by Swader** [comment]
You need to let it sync.

**Comment by COLUD4** [comment]
![截屏2021-11-30 下午7 39 15](https://user-images.githubusercontent.com/21240219/144040800-98f17690-53b5-482b-817e-356616496d7a.png)
https://github.com/rmrk-team/rmrk-tools/issues/78#issuecomment-982526410

**Comment by Yuripetusko** [comment]
> ![截屏2021-11-30 下午7 39 15](https://user-images.githubusercontent.com/21240219/144040800-98f17690-53b5-482b-817e-356616496d7a.png) [#78 (comment)](https://github.com/rmrk-team/rmrk-tools/issues/78#issuecomment-982526410)

But this is clearly running in Kusama mode

**Comment by COLUD4** [comment]
Which mode should it run in. I can't find the -chain parameter to run RMRK in the documentation

**Comment by Yuripetusko** [comment]
which documentation? I am still not sure what is your use case. We don't have any documentation about running a statemine node to query a RMRK asset. Depending on what you are trying to do. Maybe simply connect to a public node?

**Comment by COLUD4** [comment]
I want to set up a public node

**Comment by Yuripetusko** [comment]
Just to be clear, if you are interested in quering RMRK token, then this is a wrong repository to ask. You better ask in Substrate chats in elements or discord. THis repository is about RMRK NFTs

**Comment by Yuripetusko** [comment]
> I want to set up a public node

Public node for what?
